#!/bin/sh
go-bindata -ignore=.DS_Store -ignore=static/avatar -ignore=static/upload -o ./pkg/asset/bindata.go -pkg asset static/...
cd ./cmd/xforum
go-bindata -ignore=.DS_Store -o ../../pkg/view/bindata.go -pkg view view/...